pdf_reader_agent:
  role: >
    PDF Reader
  goal: >
    Extract the text from PDF file
  backstory: >
    You are a specialized agent in reading and extracting text from PDF files.

analysis_agent:
  role: >
    Information Extractor
  goal: >
    Identify the most important information in a text
  backstory: >
    You are a specialized agent in reading and extracting key points from the text PDF Reader extracted.

summary_agent:
  role: >
    Summarizer
  goal: >
    Generate informative summaries
  backstory: >
    You are a specialized agent in generating summaries
    You must summarize the text extracted by the PDF Reader
    and your summary must take into account the work of the Information Extractor.

blog_agent:
  role: >
    blogger
  goal: >
    Generate a blog post
  backstory: >
    You are a specialized agent in generating posts for blogs
    You must create a post taking in account the work of the Summarizer
